import { useEffect, useState } from 'react';

// The replay viewer's static card-data assets (public/card-*.json, generated by
// `npm run gen:card-data`) share one loader: fetched once per URL and module-cached so every
// replay in the session shares a single round-trip; a failed fetch logs, resolves to an empty
// map, and drops the cache so a later mount can retry instead of reusing the rejection forever.
const cache = new Map<string, Promise<Record<string, unknown>>>();

export function loadStaticJson<T extends Record<string, unknown>>(url: string, warn: string): Promise<T> {
    let p = cache.get(url) as Promise<T> | undefined;
    if (!p) {
        p = fetch(url)
            .then((res) => {
                if (!res.ok) throw new Error(`${url} ${res.status}`);
                // Null-prototype: a card id of `__proto__` in a file resolved to Object.prototype
                // through a plain object, and that reached a React child / localeCompare.
                return res.json().then((m: T) => Object.assign(Object.create(null) as T, m));
            })
            .catch((err) => {
                console.warn(warn, err);
                cache.delete(url);
                return Object.create(null) as T;
            });
        cache.set(url, p);
    }
    return p;
}

/** Hook: the map, empty until the JSON loads, so a first paint is never blocked on it. */
export function useStaticJson<T extends Record<string, unknown>>(url: string, warn: string): T {
    const [map, setMap] = useState<T>(() => Object.create(null) as T);
    useEffect(() => {
        let active = true;
        loadStaticJson<T>(url, warn).then((m) => { if (active) setMap(m); });
        return () => { active = false; };
    }, [url, warn]);
    return map;
}
