import type { Metadata } from "next";
import dynamic from "next/dynamic";
import "./globals.css";
import { Barlow } from "next/font/google";

const barlow = Barlow({
  subsets: ["latin"],
  weight: ["400", "800"],
  variable: "--font-barlow",
});

const ClientProviders = dynamic(
  () => import("@/app/_components/ClientProviders/ClientProviders"),
  { ssr: false }
);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${barlow.variable} font-sans`}>
      <body>
        <ClientProviders>{children}</ClientProviders>
      </body>
    </html>
  );
}
