name: Pull Request Checks
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
  merge_group:
# this will cancel any PR runs that are superseded by a new commit so they don't waste time running tests that are no longer relevant
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    if: github.event_name == 'merge_group' || github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"
      - run: npm ci
      - run: npm run lint

  build:
    if: github.event_name == 'merge_group' || github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"
      - run: npm ci
      - run: npm run build
