name: Pull Request Checks
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
jobs:
  lint:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: '22.x'
            cache: 'npm'
        - run: npm install

        - run: npm run lint